{% set name = "pyobis" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobis-{{ version }}.tar.gz
  sha256: f59318efefdd5072f985132e61e0d8920f93706dbdaf721657c3296aa5a4b10f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=41.2
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.7
    - requests >2.7
    - pandas

test:
  imports:
    - pyobis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iobis/pyobis
  summary: Python client for OBIS
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
