{% set name = "pyobis" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyobis-{{ version }}.tar.gz
  sha256: bfcc925fff9521b4484a40b6c18c75b539c0ae1553c2d11523e46b5a599be886

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41.2
    - setuptools-scm
    - wheel
    - pip
  run:
    - requests-cache >=1.2.0,<2.0.0
    - python >={{ python_min }}
    - requests >2.7
    - pandas

test:
  imports:
    - pyobis
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/iobis/pyobis
  summary: Python client for OBIS
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
