{% set name = "pyobis" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobis-{{ version }}.tar.gz
  sha256: a9ebf06b673433ba1149f85f4ded7cc10994466b2df7276fbff47b967451de79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - requests >=2.7
    - pandas

test:
  imports:
    - pyobis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iobis/pyobis
  summary: Python client for OBIS
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
